name: PR Greetings

on:
  pull_request:
    types: [opened]

jobs:
  pr-greetings:
    runs-on: ubuntu-latest
    steps:
      - name: Greet PR opener
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.GH_ACTION_TOKEN }}
          script: |
            const greeting = `Hello, @${{ github.event.pull_request.user.login }}! Thank you for opening this pull request.`;
            const { data: comment } = await octokit.rest.pulls.createReviewComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: greeting
            });
            console.log(`Comment created: ${comment.html_url}`);
