name: Validate branch name

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  validate_branch_name:
    runs-on: ubuntu-latest
    steps:
    - name: Check branch name
      run: |
        branch_name=$(echo ${{ github.head_ref }} | awk -F/ '{print $NF}')
        regex="^(TCO|PROJ)-[0-9]+$"
        if ! [[ "$branch_name" =~ $regex ]]; then
          echo "::set-output name=needs_comment::true"
          echo "::set-output name=comment_body::Branch name must match pattern 'TCO-123456' or 'PROJ-98323'."
        fi
      id: branch_check

    - name: Comment on pull request
      uses: actions/github-script@v3
      if: steps.branch_check.outputs.needs_comment == 'true'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          if (steps.branch_check.outputs.needs_comment == 'true') {
            const body = {
              body: steps.branch_check.outputs.comment_body
            };
            await github.pulls.createReviewComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: context.payload.pull_request.number,
              body: body.body
            });
          }